.\"
.\" Created by hand based off of the "man" man page
.\"
.\" Man page for prete
.\"
.\" Copyright (c) 2017, Ilan H. Bigio
.\"
.\" You may not distribute.
.\"
.\" Ilan H. Bigio
.\" ibigio@cs.brown.edu
.\" Department of Computer Science
.\" Brown University
.\" Providence, Rhode Island  02912
.\"
.\"
.TH prete 1 "August 24, 2017"
.LO 1
.SH NAME
prete \- test command that prints its non\-existance
.SH SYNOPSIS
.B prete 

.SH DESCRIPTION
.B prete
prints out the path for the
.B prete
command, followed by 'does not exist.'
Its main use is to locate the
.I bin
directory where the other custom commands are stored. Also used as a
proof of concept for creating a
.I man\-page
entry.

.SH AUTHOR
Ilan H. Bigio was the original author of
.BR "prete" .

.SH "SEE ALSO"
apropos(1), whatis(1), less(1), groff(1), man.conf(5).
