.\"
.\" Created by hand based off of the "man" man page
.\"
.\" Man page for sublime
.\"
.\" Copyright (c) 2017, Ilan H. Bigio
.\"
.\" You may not distribute.
.\"
.\" Ilan H. Bigio
.\" ibigio@cs.brown.edu
.\" Department of Computer Science
.\" Brown University
.\" Providence, Rhode Island  02912
.\"
.\"
.TH sublime 1 "December 2, 2017"
.LO 1
.SH NAME
sublime \- opens Sublime Text application
.SH SYNOPSIS
.B sublime [file]

.SH DESCRIPTION
.B sublime
opens Sublime Text, with
.B file
loaded if specified.

.SH AUTHOR
Ilan H. Bigio was the original author of
.BR "sublime" .

.SH "SEE ALSO"
prete(1).
